--- effective screen dimensions
GAME_WIDTH, GAME_HEIGHT = 512, 288

MENU_WIDTH, MENU_HEIGHT = GAME_WIDTH * 0.6, GAME_HEIGHT * 0.6
MENU_OFFSET = { (GAME_WIDTH - MENU_WIDTH) * 0.5, (GAME_HEIGHT - MENU_HEIGHT) * 0.5 }
MENU_CENTER = { MENU_WIDTH * 0.5, MENU_HEIGHT * 0.5 }
MENU_BACKGROUND = { 0, 0, 0, 0.3 }
MENU_ACTIVE = { 1, 1, 1, 1 }
MENU_INACTIVE = { 1, 1, 1, 0.7 }

SCREEN = {
	SNAKE = 1,
}

MENU = {
	MAIN = 1,
	SETTINGS = 2,
}
